DesignAccelerator/Models/ViewModel/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DA.BusinessLayer;
using DA.DomainModel;

namespace DesignAccelerator.Models.ViewModel
{
    public class ChangePasswordViewModel
    {
        #region Properties
        //tbl_ChangePassword
        public int userId { get; set; }
        [Required(ErrorMessage = "User Name is required")]
        [RegularExpression(@"^[a-zA-Z0-9_ ]*$", ErrorMessage = "Special Characters are not allowed in this field")]
        public string userName { get; set; }
        [Required(ErrorMessage = "Old Password is required")]
        public string oldPassword { get; set; }
        [Required(ErrorMessage = "New Password is required")]
        public string newPassword { get; set; }
        [Required(ErrorMessage = "Confirm Password is required")]
        public string confirmPassword { get; set; }
        #endregion
        public IList<tbl_UserData> lstUserData { get; set; }

        public void GetUserDetails()
        {
            try
            {
                UserManager userManager = new UserManager();
                lstUserData = new List<tbl_UserData>();

                lstUserData = userManager.GetUserDetails();
            }
            catch (Exception)
            {

                throw;
            }

        }

        public void UpdateChangePwdUser(tbl_UserData tblUserData)
        {
            try
            {
                tblUserData.EntityState = DA.DomainModel.EntityState.Modified;

                UserManager userManager = new UserManager();
                userManager.UpdateUserData(tblUserData);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public UserModel FindChangePwdUser(int? userId)
        {
            try
            {
                UserModel userModel = new UserModel();
                UserManager userManager = new UserManager();

                var usr = userManager.FindUserData(userId);

                userModel.userId = usr.UserID;
                userModel.userName = usr.UserName;
                userModel.password = usr.Password;

                return userModel;
            }
            catch (Exception)
            {

                throw;
            }

        }
    }
}

DesignAccelerator/Controllers/ChangePasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using DesignAccelerator.Models.ViewModel;
using DA.BusinessLayer;
using DA.DomainModel;

namespace DesignAccelerator.Controllers
{
    public class ChangePasswordController : Controller
    {
        ErrorLogViewModel errorlogviewmodel;
        // GET: ChangePassword
        [NoDirectAccess]
        public ActionResult Index()
        {
            try
            {

                return View();
            }

            catch(Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
            
        }

        [HttpPost]
        public ActionResult Index(ChangePasswordViewModel changePasswordViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserManager userManager = new UserManager();
                    tbl_UserData tblUserData = null;
                    tblUserData = userManager.FindUserName(changePasswordViewModel.userName.Trim());
                    
                    if (tblUserData != null)
                    {
                        if (tblUserData.Password.Trim().ToLower() != changePasswordViewModel.oldPassword.Trim().ToLower())
                        {
                            ViewBag.Message = "Old password does not match.";

                            return View("Index", changePasswordViewModel);

                        }
                        else
                        {
                            tblUserData.Password = changePasswordViewModel.newPassword;
                            changePasswordViewModel.UpdateChangePwdUser(tblUserData);
                            ViewBag.Message = "New password changed Successfully..";

                            return View("Index", changePasswordViewModel);
                        }
                    }
                    else
                    {
                        ViewBag.Message = "User does not exists";
                      
                    }
                }
                return View("Index", changePasswordViewModel);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }
    }
}

DesignAccelerator/Controllers/LoginController.cs
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using DesignAccelerator.Models;
using Microsoft.Owin.Security;
using System.Collections.Generic;
using DesignAccelerator.Models.ViewModel;
using System.Linq;
using DA.BusinessLayer;
using DA.DomainModel;
using System;

namespace DesignAccelerator.Controllers
{
    public class LoginController : Controller
    {
        ErrorLogViewModel errorlogviewmodel;
        private static LoginViewModel loginViewModel;

        [AllowAnonymous]
        public virtual ActionResult Index()
        {
            try
            {


                loginViewModel = new LoginViewModel();
                loginViewModel.UserTypes = new List<UserType>
            {
                new UserType{ID ="1", Type = "Internal"},
                new UserType{ID ="2", Type = "External"}
            };

                ViewData["UserTypeID"] = "1";
                return View(loginViewModel);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }


        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Index(LoginViewModel model, string returnUrl)
        {
            try
            {
                bool userflag = false;
                tbl_UserData currentUserData;

                model.UserTypes = new List<UserType>
                {
                new UserType{ID ="1", Type = "Internal"},
                new UserType{ID ="2", Type = "External"}
                };

                if (!ModelState.IsValid)
                {
                    ViewData["UserTypeID"] = model.UserTypeId;
                    return View(model);
                }


                //  model.roleID = model.GetRoleID(model.ID);

                //model.UserTypeId = "1";

                if (model.UserTypeId == "1")
                {
                    model.UserTypeId = "1";
                    ViewData["UserTypeID"] = 1;

                    // usually this will be injected via DI. but creating this manually now for brevity
                    IAuthenticationManager authenticationManager = HttpContext.GetOwinContext().Authentication;
                    currentUserData = model.CheckUser(model.Username);

                    Session["CurrentLoggedInUserDetails"] = currentUserData;
                    

                    if (currentUserData != null)
                    {
                        userflag = true;
                    }

                    if (userflag)
                    {
                        if (currentUserData.Active == "1")
                        {
                            var authService = new AuthenticationService(authenticationManager);

                            var authenticationResult = authService.SignIn(model.Username, model.Password);



                            if (authenticationResult.IsSuccess)
                            {
                                return RedirectToLocal(returnUrl);
                            }

                            ModelState.AddModelError("", authenticationResult.ErrorMessage);
                        }
                        else
                        {
                            ViewBag.Message = "User is Inactive..please contact your administrator";
                            return View(loginViewModel);
                        }
                    }
                    else
                    {
                        ViewBag.Message = "User does not exist..please contact your administrator";
                        return View(loginViewModel);
                        //return View("Error");
                    }

                }
                else
                {
                    model.UserTypeId = "2";
                    ViewData["UserTypeID"] = 2;


                    //getting the role id of the person who logs in 
                    var roleId = loginViewModel.GetRoleID(model.Username, model.Password);

                    model.lstActionType = loginViewModel.GetMappedScreenRoles(roleId);

                  
                    //Form Authentication
                    IAuthenticationManager authenticationManager = HttpContext.GetOwinContext().Authentication;

                    currentUserData = model.CheckUser(model.Username, model.Password);

                    Session["CurrentLoggedInUserDetails"] = currentUserData;

                    if (currentUserData != null)
                    {
                        userflag = true;
                    }

                    //if (model.CheckUser().Any(a => a.userName == model.Username && a.password == model.Password))// && a.Status == true))
                    if (userflag)
                    {
                        if (currentUserData.Active == "1")
                        {
                            var authService = new AuthenticationService(authenticationManager);
                            authService.SignInExternalUser(model.Username, model.Password);

                            return RedirectToLocal(returnUrl);
                        }
                        else
                        {
                            ViewBag.Message = "User is Inactive..please contact your administrator";
                            return View(loginViewModel);
                        }
                    }
                    else
                    {
                        ViewBag.Message = "Invalid login attempt.";
                        return View(loginViewModel);
                        //ModelState.AddModelError("", "Invalid login attempt.");
                    }
                }

               
                return View(model);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }

        [ValidateAntiForgeryToken]
        public virtual ActionResult Logoff()
        {
            try
            {


                IAuthenticationManager authenticationManager = HttpContext.GetOwinContext().Authentication;
                authenticationManager.SignOut(MyAuthentication.ApplicationCookie);
                Session.Remove("CurrentLoggedInUserDetails");

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }


        private ActionResult RedirectToLocal(string returnUrl)
        {
            try
            {


                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                return RedirectToAction("Index", "Client");
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }
    }


    public class LoginViewModel
    {
        
        [Required, AllowHtml]
        public string Username { get; set; }

        [Required]
        [AllowHtml]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public int roleID { get; set; }

        public string UserTypeId { get; set; }
        public List<UserType> UserTypes { get; set; }
        public IList<tbl_UserData> lstUserData { get; set; }
        public IList<tbl_RoleScreenMapping> lstActionType { get; set; }

        public int GetRoleID(string userName, string password)
        {
            try
            {


                UserManager userManager = new UserManager();
                int roleId = userManager.FindRoleID(userName, password);

                return roleId;
            }
            catch (Exception)
            {
                throw;
            }
        }

        public IList<tbl_RoleScreenMapping> GetMappedScreenRoles(int roleId)
        {
            try
            {


                UserManager userManager = new UserManager();
                lstActionType = userManager.GetMappedIDs(roleId);

                return lstActionType;
            }
            catch (Exception)
            {
                throw;
            }
        }

        public IEnumerable<UserModel> getUsers()
        {
            try
            {


                IList<UserModel> users = new List<UserModel>();
                // UserManager userManager = new UserManager();
                //lstUserData = new List<tbl_UserData>();
                
                //lstUserData = userManager.GetUserDetails();

                users.Add(new UserModel() { userId = 1, userName = "admin", Status = true });
                users.Add(new UserModel() { userId = 2, userName = "invite", Status = false });

                return users.ToList();
            }
            catch (Exception)
            {
                throw;
            }
        }

        public tbl_UserData CheckUser(string UserName)
        {
            try
            {


                //bool bCheck = false;
                UserManager userManager = new UserManager();                

                tbl_UserData userdata = userManager.FindUserName(UserName);
                
                return userdata;

            }
            catch (Exception)
            {
                throw;
            }
        }

        public tbl_UserData CheckUser(string UserName, string Password)
        {
            try
            {
               // bool bCheck = false;
                UserManager userManager = new UserManager();

DesignAccelerator/Views/ChangePassword/Index.cshtml
@using DesignAccelerator.Models.ViewModel
@model ChangePasswordViewModel

@{
    ViewBag.Title = "Change Password";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    .button {
        background-color: #af2024;
        color: #ffffff;
    }
</style>

<h2>Change Password</h2>
<hr style="width:75%;"/>

<div class="row">
    <div class="col-md-12">
        <section id="ChangePasswordForm">
            @using (Html.BeginForm("Index", "ChangePassword", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(m => m.userName, "User Name*", new { @class = "col-md-2 control-label", @style = "text-align:left" })
                    <div class="col-md-10">
                        <span class="form-inline" style="margin-left:-30px">
                            @Html.TextBoxFor(m => m.userName, new { @maxlength = "50", @class = "form-control", @style = "width:200px" })
                            @Html.ValidationMessageFor(m => m.userName, "", new { @class = "text-danger" })
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.oldPassword, "Old Password*", new { @class = "col-md-2 control-label", @style = "text-align:left" })
                    <div class="col-md-10">
                        <span class="form-inline" style="margin-left:-30px">
                            @Html.TextBoxFor(m => m.oldPassword, new { @maxlength = "25", @class = "form-control", @style = "width:200px" })
                            @Html.ValidationMessageFor(m => m.oldPassword, "", new { @class = "text-danger" })
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.newPassword, "New Password*", new { @class = "col-md-2 control-label", @style = "text-align:left" })
                    <div class="col-md-10">
                        <span class="form-inline" style="margin-left:-30px">
                            @Html.TextBoxFor(m => m.newPassword, new { @maxlength = "25", @class = "form-control", @style = "width:200px" })
                            @Html.ValidationMessageFor(m => m.newPassword, "", new { @class = "text-danger" })
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.confirmPassword, "Confirm Password*", new { @class = "col-md-2 control-label", @style = "text-align:left" })
                    <div class="col-md-10">
                        <span class="form-inline" style="margin-left:-30px">
                            @Html.TextBoxFor(m => m.confirmPassword, new { @maxlength = "25", @class = "form-control", @style = "width:200px" })
                            @Html.ValidationMessageFor(m => m.confirmPassword, "", new { @class = "text-danger" })
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10" style="margin-left:165px">
                        <input id="btnSave" type="submit" value="Add" name="action:Add" onclick="" class="btn btn-default; button" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

<div>
    <a href="@Url.Action("Index", "Login")">Back</a>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).ready(function(){$("#userName").focus();})
         @*@Html.Raw(ViewBag.abc);*@

            $("#userName").blur(function (e) {
                var userName = $.trim($("#userName").val());
                if (userName == '')
                    $('#userName').css('border-color', 'red');
                else
                    $('#userName').css('border-color', '');
            })

            $("#oldPassword").blur(function (e) {
                var oPassword = $.trim($("#oldPassword").val());
                if (oPassword == '')
                    $('#oldPassword').css('border-color', 'red');
                else
                    $('#oldPassword').css('border-color', '');
                    
            })

            $("#newPassword").blur(function (e) {
                var nPassword = $.trim($("#newPassword").val());
                if (nPassword == '')
                    $('#newPassword').css('border-color', 'red');
                else
                    $('#newPassword').css('border-color', '');

            })

            $("#confirmPassword").blur(function (e) {

                var cPassword = $.trim($("#confirmPassword").val());
                if (cPassword == '')
                    $('#confirmPassword').css('border-color', 'red');
                else {
                    $('#confirmPassword').css('border-color', '');
                    if (!Validate()) {
                        alert("New Password and Confirm Password does not match");
                        $("#confirmPassword").focus();
                    }
                }
            })

            function Validate() {
              
                var nPassword = $("#newPassword").val().trim();
                
                var confirmPassword = $("#confirmPassword").val().trim();
                //confirmPassword = $.trim(confirmPassword);

                var usrName = $("#userName").val().trim();
                //usrName = $.trim(usrName);

                if (nPassword == confirmPassword) {
                    return true;
                }
                else {
                    return false;
                }
            }

            $("#btnSave").on("click", function (e) {
                //var oPassword = $("#oldPassword").val();
                //oPassword = $.trim(oPassword);
               
                var nPassword = $("#newPassword").val().trim();
                
                var cPassword = $("#confirmPassword").val().trim();
                
                var oPassword = $("#oldPassword").val().trim();

                var userName = $("#userName").val().trim();

                if (userName == '') {
                    alert("Please enter User Name");
                    e.preventDefault();
                }

                if (oPassword == '') {
                    alert("Please enter Old Password");
                    e.preventDefault();
                }
               
                if (nPassword != cPassword) {
                    //if (!Validate()) {
                        alert("Password does not match");
                        e.preventDefault();
                    //}
                }
               
              
                //if (nPassword != cPassword) {
                //}
                //else {
                //    alert("Please enter password");
                //    e.preventDefault();
                //}
            })

        })
    </script>

    @if (ViewBag.Message != null)
        {
        <script>
                alert('@ViewBag.Message');
                $("#userName").val("");
                $('#oldPassword').val("");
                $('#newPassword').val("");
                $('#confirmPassword').val("");
        </script>
    }
}