DesignAccelerator/Models/ViewModel/ClientViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using DA.BusinessLayer;
using DA.DomainModel;

namespace DesignAccelerator.Models.ViewModel
{
    public class ClientViewModel  
    {
        #region Public properties

        public int ClientID { get; set; }
        [RegularExpression(@"^[a-zA-Z0-9_ ]*$", ErrorMessage = "Special Characters are not allowed in this field")]
        [Required(ErrorMessage = "Client Name required")]
        public string ClientName { get; set; }

        public int roleId { get; set; }
        public string RoleName { get; set; }

        public bool AddPermmission = false;
        public bool EdiPermission = false;
        public bool DeletePermission = false;

        #endregion

        public void AddClient(ClientViewModel clientViewModel)
        {
            try
            {
                tbl_Clients tblClient = new tbl_Clients();

                tblClient.ClientName = clientViewModel.ClientName;
                tblClient.EntityState = DA.DomainModel.EntityState.Added;

                ClientManager clientManager = new ClientManager();

                clientManager.AddClient(tblClient);
            }
            catch(Exception)
            {
                throw;
            }
        }

        public bool DeleteClient(ClientViewModel clientViewModel)
        {            
            try
            {
                tbl_Clients tblClient = new tbl_Clients();

                tblClient.ClientID = clientViewModel.ClientID;
                tblClient.EntityState = DA.DomainModel.EntityState.Deleted;

                ClientManager clientManager = new ClientManager();
                clientManager.DeleteClient(tblClient);
            }
            catch (Exception)
            {
                throw;
            }         

            return true;
        }

        public void UpdateClient(ClientViewModel clientViewModel)
        {
            try
            {
                tbl_Clients tblClient = new tbl_Clients();

                tblClient.ClientID = clientViewModel.ClientID;
                tblClient.ClientName = clientViewModel.ClientName;
                tblClient.EntityState = DA.DomainModel.EntityState.Modified;

                ClientManager clientManager = new ClientManager();
                clientManager.UpdateClient(tblClient);
            }
            catch(Exception)
            {
                throw;
            }
        }

        public IList<ClientViewModel> ClientList { get; set; }

        public void GetClientDetails()
        {
            try
            {
                ClientManager clientManager = new ClientManager();
                var clientList = clientManager.GetClientDetails();
                ClientList = new List<ClientViewModel>();
                foreach (var item in clientList)
                {
                    ClientViewModel Client = new ClientViewModel();

                    Client.ClientID = item.ClientID;
                    Client.ClientName = item.ClientName;

                    ClientList.Add(Client);
                }
            }
            catch(Exception)
            {
                throw;
            }
          }

        public ClientViewModel FindClient(int? clientID)
        {
            try
            {
                ClientViewModel clientViewModel = new ClientViewModel();

                ClientManager clientManager = new ClientManager();
                var client = clientManager.FindClient(clientID);

                clientViewModel.ClientID = client.ClientID;
                clientViewModel.ClientName = client.ClientName;

                return clientViewModel;
            }
            catch (Exception)
            {
                throw;
            }
        }

        public bool CheckDuplicate(ClientViewModel clientViewModel)
        {
            try
            {
                ClientManager clientManager = new ClientManager();

                var client = clientManager.FindClientName(clientViewModel.ClientName);

                if (client != null && client.ClientID != clientViewModel.ClientID && client.ClientName.ToUpper() == clientViewModel.ClientName.ToUpper())
                {
                    return true;
                }
                return false;
            }
            catch (Exception)
            {
                throw;
            }
        }


        public void GetScreenAccessRights(string  screenName)
        {
            try
            {
                tbl_UserData currentloggedinuserdata = (tbl_UserData)HttpContext.Current.Session["CurrentLoggedInUserDetails"];
                roleId = currentloggedinuserdata.RoleID;

                RoleManager roleManager = new RoleManager();
                var userrolepermissions = roleManager.GetUserViewAccessPermissions(screenName, roleId);
               
                foreach (var item in userrolepermissions)
                {
                    if (item.ActionType == "Add")
                        AddPermmission = true;
                    else if (item.ActionType == "Edit")
                        EdiPermission = true;
                    else if (item.ActionType == "Delete")
                        DeletePermission = true;

                    RoleName = item.RoleName;                     
                }                    
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

DesignAccelerator/Controllers/AuthUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DesignAccelerator.Models.ViewModel;

namespace DesignAccelerator.Controllers
{
    public class AuthUserController : Controller
    {
        ErrorLogViewModel errorlogviewmodel;
        AuthUserViewModel myauthuserViewModel;

        // GET: AuthUser
        [NoDirectAccess]        
        public ActionResult Index()
        {
            try
            {
                myauthuserViewModel = new AuthUserViewModel();
               // List<AuthUserViewModel> lstauthuserViewModel = new List<AuthUserViewModel>();
               
                 myauthuserViewModel.getAuthUsersFrmDB();

                ViewBag.Numberofauthusers = myauthuserViewModel.lstauthusers.Count;

                return View(myauthuserViewModel.lstauthusers);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");

            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FormCollection form)
        {
            try
            {
                myauthuserViewModel = new AuthUserViewModel();

                if (ModelState.IsValid)
                {
                    var chckedValues = form.GetValues("chkStatus");
                    
                    foreach (var id in chckedValues)
                    {
                       int id1 = Convert.ToInt32(id);
                        myauthuserViewModel.UpdateUserActive(id1);
                    }

                    myauthuserViewModel.getAuthUsersFrmDB();

                    ViewBag.Numberofauthusers = myauthuserViewModel.lstauthusers.Count;

                }
                return View(myauthuserViewModel.lstauthusers);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }
    }
}

DesignAccelerator/Controllers/ClientController.cs
using System;
using System.Web.Mvc;
using DesignAccelerator.Models.ViewModel;
using System.Net;
using System.Data.SqlClient;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;

namespace DesignAccelerator.Controllers
{
    public class ClientController : Controller
    {

        #region PublicProperties
        ErrorLogViewModel errorlogviewmodel;        
        #endregion

        // GET: Client
        [Authorize]
        public ActionResult Index()
        {
            try
            {
                ClientViewModel clientViewModel = new ClientViewModel();
                //if (id == null)
                //    id = (int)TempData["ClientId"];
                clientViewModel.GetClientDetails();
                clientViewModel.GetScreenAccessRights("Client Details");
                //clientViewModel.ClientID = (int)id;
                
                //int ClientId;

                //CommonFunctions comfuns = new CommonFunctions();
                //var da = comfuns.FindDA((int)id);
                //clientViewModel.daid = (int)id;

                return View(clientViewModel);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }

        [HttpPost]        
        public ActionResult Index(ClientViewModel clientViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isDuplicate = false;
                    clientViewModel.ClientName = clientViewModel.ClientName.Trim();
                    isDuplicate = clientViewModel.CheckDuplicate(clientViewModel);

                    if (isDuplicate)
                    {
                        clientViewModel.GetClientDetails();
                        ViewBag.Message = "Client Already Exists";
                        clientViewModel.GetScreenAccessRights("Client Details");
                        return View("Index",clientViewModel);
                    }
                    else
                    {
                        clientViewModel.AddClient(clientViewModel);
                        clientViewModel.GetClientDetails();
                        ViewBag.Message = "New Client Added Successfully";
                        clientViewModel.GetScreenAccessRights("Client Details");
                        return View("Index", clientViewModel);
                    }
                }
                clientViewModel.GetClientDetails();
                clientViewModel.GetScreenAccessRights("Client Details");
                return View(clientViewModel);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");               
            }
        }

        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ClientViewModel clientViewModel = new ClientViewModel();
                var client = clientViewModel.FindClient(id);

                if (client == null)
                {
                    return HttpNotFound();
                }
                return View(client);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ClientViewModel clientViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    clientViewModel.DeleteClient(clientViewModel);
                    return RedirectToAction("Index", "Client");
                }
                return RedirectToAction("Index", "Client");
            }
            catch (DbUpdateException exception)
            {
                //Log Exception
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(exception);

                //Check for Referential Integrity
                if (((System.Data.SqlClient.SqlException)exception.InnerException.InnerException).Number == 547)
                {
                    return View("Error_ReferentialIntegrity");
                }

                return View("Error");
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");
            }
        }

        //// GET: /User/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ClientViewModel clientViewModel = new ClientViewModel();
                var client = clientViewModel.FindClient(id);

                if (client == null)
                {
                    return HttpNotFound();
                }
                return View(client);
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");                
            }
        }

        //POST: /User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClientViewModel clientViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    clientViewModel.ClientName = clientViewModel.ClientName.Trim();
                    bool isDuplicate = false;
                    isDuplicate = clientViewModel.CheckDuplicate(clientViewModel);
                    if (isDuplicate)
                    {
                        ModelState.AddModelError("ClientName", "Client already exists");
                        return View("Edit", clientViewModel);
                    }

                    clientViewModel.UpdateClient(clientViewModel);
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                errorlogviewmodel = new ErrorLogViewModel();
                errorlogviewmodel.LogError(ex);
                return View("Error");                
            }
        }
    }
}

DesignAccelerator/Views/Client/Delete.cshtml
@model DesignAccelerator.Models.ViewModel.ClientViewModel

<style>
    .button {
        background-color: #af2024;
        color: #ffffff;
    }
</style>
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Delete Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClientID)
        
        <div class="form-group">
            @Html.Label("Client Name", htmlAttributes: new { @class = "control-label col-md-2", @style = "text-align:left" })
            <div class="col-md-10">
                <span class="form-inline" style="margin-left:-100px">
                    @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                    @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                </span>
            </div>
        </div>

        <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="margin-left:95px">
                    <input type="submit" value="Delete" name="action:Delete" class="btn btn-default; button" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back", "Index")
</div>

DesignAccelerator/Views/Client/Edit.cshtml
@model DesignAccelerator.Models.ViewModel.ClientViewModel

<style>
    .button {
        background-color: #af2024;
        color: #ffffff;
    }
</style>

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClientID)

        <div class="form-group">
            @Html.Label("Client Name", htmlAttributes: new { @class = "control-label col-md-2", @style = "text-align:left" })
            <div class="col-md-10">
                <span class="form-inline" style="margin-left:-100px">
                    @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @maxlength = "50", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="margin-left:95px">
                <input type="submit" value="Save" class="btn btn-default; button" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Index")
</div>

@section scripts{
    <script>
        $("#ClientName").bind('keypress', function (event) {

            var regex = new RegExp("^[a-zA-Z0-9]+$");
            var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
            if (!regex.test(key)) {
                if (event.charCode != 32) {//if key stroke is space bar, then pass. ASCII code for space bar is 32
                    event.preventDefault();
                    return false;
                }
            }
        });

       
    </script>
    }

DesignAccelerator/Views/Client/Index.cshtml
@model DesignAccelerator.Models.ViewModel.ClientViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .button {
        background-color: #af2024;
        color: #ffffff;
    }
</style>

<div  class="navbar-static-top">
    <div id="Adminactivities" class="breadcrumb">
        <a style="color:white;" class="" id="linkToUsr" href="@Url.Action("Index", "User", new {})">Create Users</a> &nbsp;&nbsp;
        <a style="color:white;" id="linkToAuthUsr" href="@Url.Action("Index", "AuthUser", new {})">Authorize Users</a>  &nbsp;&nbsp;
        <a style="color:white;" id="linkToRoles" href="@Url.Action("Index", "Role", new {})">Create Roles</a> &nbsp;&nbsp;
        <a style="color:white;" id="idRolePermission" href="@Url.Action("Index", "RolesPermissions", new {})">Access Rights</a> &nbsp;&nbsp;
        <a style="color:white;" id="linkToMISReports" href="@Url.Action("Index", "MISReports", new {})">MISReports</a> &nbsp;&nbsp;
    </div>
</div>

<h2>Client Details</h2>
<hr />

<div class="row">
    <div class="col-md-12">
        <section id="ClientForm">
            @using (Html.BeginForm("Index", "Client", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "formId" })) 
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.Label("Client Name*", new { @class = "col-md-2 control-label", @style = "text-align:left" })
                    <div class="col-md-4">
                        <span class="form-inline" style="margin-left:-100px">
                            @Html.TextBoxFor(m => m.ClientName, new { @maxlength = "50", @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(m => m.ClientName, "", new { @class = "text-danger" })
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10" style="margin-left:95px">
                        <input id="btnSave" type="submit" value="Add" name="action:Add" class="btn btn-default; button" disabled="disabled" />
                        @*&nbsp;&nbsp;&nbsp;<input id="btnExportToExcel" type="submit" value="ExportToExcel" name="action:Export" class="btn btn-default" />*@
                        @*<input type="submit" value="Cancel" onclick="Cancel()" class="btn btn-default" />*@                      
                        
                    </div>
                </div>               
            }
</section>
    </div>
</div>
<hr />
<div id="gridId" style="width:50%;">

    @{
        try
        {
            
            WebGrid grid = new WebGrid(Model.ClientList);
            @grid.GetHtml(
                           tableStyle: "table table-bordered table-hover",
                           fillEmptyRows: false,
                           headerStyle: "gvHeading",
                           alternatingRowStyle: "gvAlternateRow",
                           rowStyle: "gvRow",
                           footerStyle: "gvFooter",
                           mode: WebGridPagerModes.All,
                           firstText: "<< First",
                           previousText: "< Prev",
                           nextText: "Next >",
                           lastText: "Last >>",
                           columns: new[] {
                                grid.Column(header: "S.No.", format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
                                grid.Column("ClientName",header: "Client Name",canSort:true, format: (item) => Html.ActionLink(((string)item.ClientName), "Index", "Project", new { id = item.ClientID }, null)),
                                grid.Column("ClientID",header:"Edit/Delete",canSort:false,
                                 format: @<text>
                                            @if(Model.EdiPermission) {
                                                @Html.ActionLink("Edit | ", "Edit", new { id=item.ClientID});
                                             }
                                            else {
                                                <text>Edit | </text>    
                                            }                                        
                            
                                            @if(Model.DeletePermission){
                                                @Html.ActionLink("Delete", "Delete", new { id=item.ClientID})
                                            }
                                            else {
                                                <text>Delete</text>
                                            }
                                    
                                        </text>
                                            )
                                            }
                                  )
        }

        catch (Exception)
        {

        }
    }
</div>

@section scripts {
    <script type="text/javascript">

        $(document).ready(function () {

            var model = @Html.Raw(Json.Encode(Model.AddPermmission));
            if (model == true)
                $('#btnSave').prop("disabled", "");
            else
                $('#btnSave').prop("disabled", "disabled");

            $('#ClientName').val("");

            var usrrole = @Html.Raw(Json.Encode(Model.RoleName));
            if (usrrole == "Admin" || usrrole == "Test Manager" || usrrole == "Business Analyst")
            {                
                $('#Adminactivities').show();               
            }
            else
            {       
                $('#Adminactivities').hide();
            }
        })
    </script>
        @*var lstActionTypes = JSON.parse('@Html.Raw(Json.Encode(ViewData["ActionTypesList"]))');

        var view = "View";

        var clientScreenID = 1;

        if (clientScreenID == 1 && view == "View") {
            //$("#formId input").prop("disabled", true);
            //$("#gridId").bind("click.myDisable", function () { return false; });
            //$("#linkToRoles").bind("click.myDisable", function () { return false; });
            //$("#linkToUsr").bind("click.myDisable", function () { return false; });
            //$("#idRolePermission").bind("click.myDisable", function () { return false; });
        }




        //code to disable all the special characters in the text box including space bar
        $("#ClientName").bind('keypress', function (event) {

            var regex = new RegExp("^[a-zA-Z0-9]+$");
            var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
            if (!regex.test(key)) {
                if (event.charCode != 32) {//if key stroke is space bar, then pass. ASCII code for space bar is 32
                    event.preventDefault();
                    return false;
                }
            }
        });*@




    

    @*@if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {

                alert('@ViewBag.Message');
                $("#ClientName").val("");

            });

        </script>
    }@*@
}